import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import {
  INSTALL_PATH,
  makeTempDir,
  removeHarness,
  runNode,
} from "./helpers.mjs";

const MARKER = "generated by the herdr tab-titles installer";

async function withHome(fn) {
  const root = await makeTempDir();
  const home = join(root, "home");
  await mkdir(join(home, ".config", "herdr"), { recursive: true });
  await mkdir(join(home, ".local", "bin"), { recursive: true });
  try {
    return await fn({ root, home });
  } finally {
    await removeHarness({ root });
  }
}

function installEnv(home) {
  return {
    ...process.env,
    HOME: home,
    CURSOR_CONFIG_DIR: join(home, ".missing-cursor"),
    OPENCODE_CONFIG_DIR: join(home, ".missing-opencode"),
  };
}

test("installs current hooks and is idempotent", async () => {
  await withHome(async ({ home }) => {
    const bashrc = join(home, ".bashrc");
    await writeFile(bashrc, "export EDITOR=nvim\n");
    const first = await runNode(INSTALL_PATH, { env: installEnv(home) });
    assert.equal(first.code, 0, first.stderr);
    const launcher = await readFile(join(home, ".local", "bin", "herdr-tab-titles"), "utf8");
    assert.match(launcher, /plugin config-dir tab-titles/);
    assert.match(launcher, /HERDR_PLUGIN_CONFIG_DIR/);
    assert.match(launcher, /herdr\/plugins\/tab-titles/);
    assert.match(launcher, new RegExp(MARKER));
    const hook = await readFile(join(home, ".local", "share", "herdr-tab-titles", "hook.bash"), "utf8");
    assert.match(hook, new RegExp(MARKER));
    const sourced = await readFile(bashrc, "utf8");
    assert.match(sourced, /export EDITOR=nvim/);
    assert.match(sourced, /herdr-tab-titles\/hook\.bash/);
    const second = await runNode(INSTALL_PATH, { env: installEnv(home) });
    assert.equal(second.code, 0, second.stderr);
    const again = await readFile(bashrc, "utf8");
    assert.equal(
      again.split('source "$HOME/.local/share/herdr-tab-titles/hook.bash"').length - 1,
      1,
    );
    assert.match(second.stdout, /already sources the process hook/);
  });
});

test("installs lifecycle hooks idempotently without replacing other hooks", async () => {
  await withHome(async ({ home }) => {
    for (const [directory, file] of [[".claude", "settings.json"], [".codex", "hooks.json"]]) {
      await mkdir(join(home, directory), { recursive: true });
      await writeFile(join(home, directory, file), JSON.stringify({ hooks: {
        SessionStart: [{ matcher: "startup", hooks: [{ type: "command", command: "echo existing" }] }],
      } }));
    }
    await runNode(INSTALL_PATH, { env: installEnv(home) });
    const snapshots = [];
    for (const [directory, file] of [[".claude", "settings.json"], [".codex", "hooks.json"]]) {
      const path = join(home, directory, file);
      const raw = await readFile(path, "utf8");
      snapshots.push([path, raw]);
      const { hooks } = JSON.parse(raw);
      assert.equal(hooks.SessionStart[0].hooks[0].command, "echo existing");
      assert.equal(hooks.SessionStart.length, 2);
      assert.match(hooks.SessionStart[1].matcher, /clear/);
      assert.equal(hooks.SessionEnd.length, 1);
      assert.equal(hooks.UserPromptSubmit.length, 1);
      assert.notEqual(hooks.SessionStart[1].hooks[0].async, true);
      assert.notEqual(hooks.SessionEnd[0].hooks[0].async, true);
    }
    await runNode(INSTALL_PATH, { env: installEnv(home) });
    for (const [path, raw] of snapshots) assert.equal(await readFile(path, "utf8"), raw);
  });
});

test("does not rewrite unrelated rc content when adding the process hook", async () => {
  await withHome(async ({ home }) => {
    const bashrc = join(home, ".bashrc");
    await writeFile(bashrc, [
      "alias notes=\"$HOME/Projects/scratch/install.mjs\"",
      "# local notes about tab titles",
      "",
    ].join("\n"));
    const result = await runNode(INSTALL_PATH, { env: installEnv(home) });
    assert.equal(result.code, 0, result.stderr);
    const next = await readFile(bashrc, "utf8");
    assert.match(next, /alias notes="\$HOME\/Projects\/scratch\/install\.mjs"/);
    assert.match(next, /# local notes about tab titles/);
    assert.match(next, new RegExp(`# ${MARKER}`));
    assert.match(next, /herdr-tab-titles\/hook\.bash/);
  });
});

test("leaves a share file it did not write alone", async () => {
  await withHome(async ({ home }) => {
    const hook = join(home, ".local", "share", "herdr-tab-titles", "hook.bash");
    await mkdir(join(home, ".local", "share", "herdr-tab-titles"), { recursive: true });
    await writeFile(hook, "# my custom process hook\necho custom\n");
    const result = await runNode(INSTALL_PATH, { env: installEnv(home) });
    assert.equal(result.code, 0, result.stderr);
    assert.equal(await readFile(hook, "utf8"), "# my custom process hook\necho custom\n");
    assert.match(result.stdout, /was not written by this installer, left alone/);
  });
});
