#!/usr/bin/env node
/**
 * Wires the plugin into whichever agents are present on this machine.
 *
 * Runs as the `[[build]]` step of `herdr plugin install`, and is safe to re-run:
 * every step is idempotent, and any file it rewrites is backed up alongside itself.
 *
 * Nothing it installs may point at this checkout. Herdr builds a plugin inside a
 * staging directory it deletes afterwards, so the launcher resolves the root
 * through `herdr plugin list` at run time and the agent integrations are copied
 * rather than linked.
 */
import { constants } from "node:fs";
import { access, chmod, copyFile, lstat, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HOME = process.env.HOME || homedir();
const ROOT = process.env.HERDR_PLUGIN_ROOT || dirname(dirname(fileURLToPath(import.meta.url)));
const BIN = join(HOME, ".local", "bin");
const PLUGIN_ID = "tab-titles";
const LAUNCHER = join(BIN, "herdr-tab-titles");
const CLAUDE_HOOK = join(BIN, "herdr-tab-titles-hook");
const CURSOR_HOOK = join(BIN, "herdr-tab-titles-cursor-hook");
const CURSOR_DIR = process.env.CURSOR_CONFIG_DIR || join(HOME, ".cursor");
const OPENCODE_DIR = process.env.OPENCODE_CONFIG_DIR || join(HOME, ".config", "opencode");
const SHARE = join(HOME, ".local", "share", "herdr-tab-titles");
const BASH_HOOK = join(SHARE, "hook.bash");
const ZSH_HOOK = join(SHARE, "hook.zsh");
const MARKER = "generated by the herdr tab-titles installer";

function ownedByInstaller(contents) {
  return contents.includes(MARKER);
}

function isOurHook(entry) {
  const command = String(entry?.command ?? "");
  return command.includes("herdr-tab-titles");
}

const LAUNCHER_SCRIPT = `#!/bin/sh
# ${MARKER}. Safe to delete; reinstalling the plugin writes it again.
# The build directory is gone by the time this runs, so resolve the root each time.
set -u
root=$("\${HERDR_BIN_PATH:-herdr}" plugin list --plugin ${PLUGIN_ID} --json 2>/dev/null | node -e '
let raw = "";
process.stdin.on("data", (chunk) => { raw += chunk; });
process.stdin.on("end", () => {
  try {
    const plugin = (JSON.parse(raw)?.result?.plugins ?? []).find((p) => p.plugin_id === "${PLUGIN_ID}");
    process.stdout.write(plugin ? (plugin.enabled === false ? "disabled" : plugin.plugin_root ?? "") : "");
  } catch {
    process.stdout.write("");
  }
});
')
case "$root" in
  disabled) exit 0 ;;
  "")
    # The renamer never runs, so this is the only trace the failure leaves.
    if [ -n "\${HERDR_PLUGIN_STATE_DIR:-}" ]; then
      state="\$HERDR_PLUGIN_STATE_DIR"
    elif [ -n "\${XDG_STATE_HOME:-}" ]; then
      state="\$XDG_STATE_HOME/herdr/plugins/${PLUGIN_ID}"
    else
      state="\$HOME/.local/state/herdr/plugins/${PLUGIN_ID}"
    fi
    mkdir -p "$state" 2>/dev/null
    printf '%s failed: launcher could not find the plugin root, is herdr on PATH?\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >>"$state/rename.log" 2>/dev/null
    exit 0 ;;
esac
if [ -z "\${HERDR_PLUGIN_CONFIG_DIR:-}" ]; then
  HERDR_PLUGIN_CONFIG_DIR=\$("\${HERDR_BIN_PATH:-herdr}" plugin config-dir ${PLUGIN_ID} 2>/dev/null) || HERDR_PLUGIN_CONFIG_DIR=""
  if [ -z "\$HERDR_PLUGIN_CONFIG_DIR" ]; then
    if [ -n "\${XDG_CONFIG_HOME:-}" ]; then
      HERDR_PLUGIN_CONFIG_DIR="\$XDG_CONFIG_HOME/herdr/plugins/config/${PLUGIN_ID}"
    else
      HERDR_PLUGIN_CONFIG_DIR="\$HOME/.config/herdr/plugins/config/${PLUGIN_ID}"
    fi
  fi
  export HERDR_PLUGIN_CONFIG_DIR
fi
if [ -z "\${HERDR_PLUGIN_STATE_DIR:-}" ]; then
  if [ -n "\${XDG_STATE_HOME:-}" ]; then
    export HERDR_PLUGIN_STATE_DIR="\$XDG_STATE_HOME/herdr/plugins/${PLUGIN_ID}"
  else
    export HERDR_PLUGIN_STATE_DIR="\$HOME/.local/state/herdr/plugins/${PLUGIN_ID}"
  fi
fi
exec node "$root/src/rename.mjs" "$@"
`;

const done = [];
const skipped = [];

async function exists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

/** Writes a generated file, refusing to clobber one this installer did not create. */
async function install(path, contents, { executable = false } = {}) {
  // lstat, not access: an earlier version of this installer left symlinks behind,
  // and a broken one reads as absent through access().
  const current = await lstat(path).catch(() => null);
  if (current && !current.isFile() && !current.isSymbolicLink()) {
    skipped.push(`${path} is not a file, left alone`);
    return;
  }
  if (current?.isFile()) {
    const previous = await readFile(path, "utf8").catch(() => "");
    if (!ownedByInstaller(previous)) {
      skipped.push(`${path} was not written by this installer, left alone (delete it to have it reinstalled)`);
      return;
    }
    if (previous === contents) {
      skipped.push(`${path} is already up to date`);
      return;
    }
  }
  if (current) await rm(path, { force: true });
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
  if (executable) await chmod(path, 0o755);
  done.push(`wrote ${path}`);
}

/** A shipped integration file with the ownership marker after its shebang, or as its first line. */
async function marked(path, comment) {
  const contents = await readFile(path, "utf8");
  const note = `${comment} ${MARKER}. Safe to delete; reinstalling the plugin writes it again.\n`;
  return contents.startsWith("#!") ? contents.replace(/^#!.*\n/, (shebang) => `${shebang}${note}`) : `${note}${contents}`;
}

/** Rewrites `path` with `update(json)`, keeping a `.bak` copy of the previous content. */
async function editJson(path, update) {
  let json = {};
  const present = await exists(path);
  if (present) {
    try {
      json = JSON.parse(await readFile(path, "utf8"));
    } catch {
      skipped.push(`${path} is not valid JSON, left alone`);
      return;
    }
  }
  const note = update(json);
  if (!note) {
    skipped.push(`${path} already has the current hook`);
    return;
  }
  if (present) await copyFile(path, `${path}.bak`);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(json, null, 2)}\n`);
  done.push(note);
}

function applyTokens(command, tokens) {
  return Object.entries(tokens).reduce(
    (text, [token, value]) => text.replaceAll(`{{${token}}}`, value),
    command,
  );
}

/**
 * The `UserPromptSubmit` hook an agent should run, read from its file under
 * `integrations/` so that the shipped snippet and what gets installed cannot drift.
 */
async function promptHookFrom(path, tokens = {}) {
  const json = JSON.parse(await readFile(path, "utf8"));
  const hook = json?.hooks?.UserPromptSubmit?.[0]?.hooks?.[0];
  if (!hook?.command) throw new Error(`${path} defines no UserPromptSubmit command hook`);
  return { ...hook, command: applyTokens(hook.command, tokens) };
}

/**
 * Cursor's native `beforeSubmitPrompt` hook, read from its file under
 * `integrations/` so that the shipped snippet and what gets installed cannot drift.
 */
async function cursorPromptHookFrom(path, tokens = {}) {
  const json = JSON.parse(await readFile(path, "utf8"));
  const hook = json?.hooks?.beforeSubmitPrompt?.[0];
  if (!hook?.command) throw new Error(`${path} defines no beforeSubmitPrompt command hook`);
  return { ...hook, command: applyTokens(hook.command, tokens) };
}

/** Adds or updates this plugin's `UserPromptSubmit` hook, leaving other hooks and any local edits alone. */
function setPromptHook(json, hook) {
  json.hooks ??= {};
  const matchers = (json.hooks.UserPromptSubmit ??= []);
  for (const matcher of matchers) {
    const existing = (matcher?.hooks ?? []).find(isOurHook);
    if (!existing) continue;
    const current = Object.entries(hook)
      .every(([key, value]) => JSON.stringify(existing[key]) === JSON.stringify(value));
    if (current) return false;
    Object.assign(existing, hook);
    return true;
  }
  matchers.push({ hooks: [hook] });
  return true;
}

/**
 * Adds or updates this plugin's native Cursor `beforeSubmitPrompt` hook.
 * Leaves Herdr's `sessionStart` entry and any other local hooks alone.
 */
function setCursorPromptHook(json, hook) {
  json.version ??= 1;
  json.hooks ??= {};
  const entries = (json.hooks.beforeSubmitPrompt ??= []);
  const existing = entries.find(isOurHook);
  if (existing) {
    const current = Object.entries(hook)
      .every(([key, value]) => JSON.stringify(existing[key]) === JSON.stringify(value));
    if (current) return false;
    Object.assign(existing, hook);
    return true;
  }
  entries.push(hook);
  return true;
}

/** Appends a source line to a shell rc file the installer has not already edited. */
async function sourceHook(rcPath, hookPath) {
  if (!await exists(rcPath)) {
    skipped.push(`${rcPath} is missing, left alone`);
    return;
  }
  const previous = await readFile(rcPath, "utf8").catch(() => "");
  const file = basename(hookPath);
  const snippet = `[[ -r "$HOME/.local/share/herdr-tab-titles/${file}" ]] && source "$HOME/.local/share/herdr-tab-titles/${file}"\n`;
  if (previous.includes(`herdr-tab-titles/${file}`)) {
    skipped.push(`${rcPath} already sources the process hook`);
    return;
  }
  await copyFile(rcPath, `${rcPath}.bak`);
  const next = `${previous.replace(/\s*$/, "")}\n\n# ${MARKER}\n${snippet}`;
  await writeFile(rcPath, next);
  done.push(`sourced the process hook from ${rcPath}`);
}

await install(LAUNCHER, LAUNCHER_SCRIPT, { executable: true });

if (await exists(join(HOME, ".pi", "agent"))) {
  await install(
    join(HOME, ".pi", "agent", "extensions", "herdr-tab-titles.ts"),
    await marked(join(ROOT, "integrations", "pi", "herdr-tab-titles.ts"), "//"),
  );
} else {
  skipped.push("Pi is not installed");
}

if (await exists(join(HOME, ".codex"))) {
  const path = join(HOME, ".codex", "hooks.json");
  const hook = await promptHookFrom(join(ROOT, "integrations", "codex-user-prompt-hook.json"), { launcher: LAUNCHER });
  await editJson(path, (json) => setPromptHook(json, hook) && `set the Codex hook in ${path}`);
} else {
  skipped.push("Codex is not installed");
}

if (await exists(join(HOME, ".claude"))) {
  await install(CLAUDE_HOOK, await marked(join(ROOT, "integrations", "claude-code", "hook.sh"), "#"), { executable: true });
  const path = join(HOME, ".claude", "settings.json");
  const hook = await promptHookFrom(
    join(ROOT, "integrations", "claude-code", "settings-hook.json"),
    { "claude-hook": CLAUDE_HOOK },
  );
  await editJson(path, (json) => setPromptHook(json, hook) && `set the Claude Code hook in ${path}`);
} else {
  skipped.push("Claude Code is not installed");
}

if (await exists(CURSOR_DIR)) {
  await install(CURSOR_HOOK, await marked(join(ROOT, "integrations", "cursor", "hook.sh"), "#"), { executable: true });
  const path = join(CURSOR_DIR, "hooks.json");
  const hook = await cursorPromptHookFrom(
    join(ROOT, "integrations", "cursor", "hooks.json"),
    { "cursor-hook": CURSOR_HOOK },
  );
  await editJson(path, (json) => setCursorPromptHook(json, hook) && `set the Cursor Agent CLI hook in ${path}`);
} else {
  skipped.push("Cursor Agent CLI is not installed");
}

if (await exists(OPENCODE_DIR)) {
  await install(
    join(OPENCODE_DIR, "plugins", "herdr-tab-titles.js"),
    await marked(join(ROOT, "integrations", "opencode", "herdr-tab-titles.js"), "//"),
  );
} else {
  skipped.push("OpenCode is not installed");
}

await install(BASH_HOOK, await marked(join(ROOT, "integrations", "shell", "hook.bash"), "#"));
await install(ZSH_HOOK, await marked(join(ROOT, "integrations", "shell", "hook.zsh"), "#"));
await sourceHook(join(HOME, ".bashrc"), BASH_HOOK);
await sourceHook(join(HOME, ".zshrc"), ZSH_HOOK);

for (const line of done) console.log(`  ${line}`);
for (const line of skipped) console.log(`  skipped: ${line}`);
console.log("\nPi sessions need /reload; restart running Codex, Claude Code, Cursor Agent CLI, and OpenCode sessions.");
console.log("Process names need a new shell, or source ~/.bashrc / ~/.zshrc in an existing pane.");
